export const REQUEST_DEALER='REQUEST_DEALER'
export const GET_DEALER_FAILURE='GET_DEALER_FAILURE'
export const GET_DEALER_SUCCESS='GET_DEALER_SUCCESS'

export const REQUEST_DRAW2CARDS='REQUEST_DRAW2CARDS'
export const GET_DRAW2CARDS_FAILURE='GET_DRAW2CARDS_FAILURE'
export const GET_DRAW2CARDS_SUCCESS='GET_DRAW2CARDS_SUCCESS'

export const REQUEST_DECK='REQUEST_DECK'
export const GET_DECK_FAILURE='GET_DECK_FAILURE'
export const GET_DECK_SUCCESS='GET_DECK_SUCCESS'